### ISSUE TITLE
Crafting recipes - PLEASE COMMENT SUGGESTIONS

### ISSUE THREAD

**Issue by Rubydesic** [ValkyrienSkies/Valkyrien-Skies#264]
Crafting recipes for everything, what does everyone think they should be & why?

**Added**

- [ ] New Physics Infuser Recipe - DeadlyForest
- [ ] New Physics Core Recipe - DeadlyForest

**Comment by zayats1** [comment]
Mod is too unstable for survival.Recipes can be create with Crafttweaker WurmTweaks or IGCM

**Comment by DeadlyForest** [comment]
http://tinyurl.com/y3npy7eg

PHYSICS INFUSER

I added this crafting recipe for my server. I believe it is good because it makes you use more of the valk ore, makes you use redstone, gold and diamond to make it more expensive and later game, and leather because leather is inconvenient to get, and flight should never be convenient or cheap

**Comment by DeadlyForest** [comment]
http://tinyurl.com/y2554ta2

PHYSICS CORE

I added this crafting recipe for my server. I believe it is good because it makes you use lots of valk crystals (adding risk to achieving the ability to fly), as well as making the player sacrifice 4 or 5 more diamonds. (Also redstone, because it seemed logical)

**Comment by Pettmybuckets** [comment]
Physics core recipe: 4 valkyrium ore in a + shape, one gold ore or ender eye in the center, and 4 diamonds in each corner.

Physics infuser: 2 oak blocks on each side, a compass in the middle, 2 levers, 2 obsidian, and 2 gold bars on top and bottom.

**Comment by Vricken** [comment]
**It should be expensive. nothing i a ship is at least that should be.
In the middle a doubled compressed valkyrium block. Surrounded by 9 core frames. Core frames should be made of 5 bronze ingots. I know that it means adding new block but it would be very cool. In my server i did like this.**

**Comment by Tri0de** [comment]
Crafting recipes are in 1.0.0.
