### ISSUE TITLE
Players fall off the ship when the ship is moving

### ISSUE THREAD

**Issue by Sunspot0411** [ValkyrienSkies/Valkyrien-Skies#45]
When ship has movement, no matter it's horizontal or vertical, players on survival mode tend to move slower then the ship and pass through blocks. This problem seems only to exist on survival mode but not creative mode.

**Comment by Rubyjunk** [comment]
Hi, and thanks for your report. This issue is being *currently* investigated and is a work in progress. **Specifically, we are reworking the entire mounting system to be much more consistent, intuitive, and compatible.** This issue will be updated as progress continues.

*Current time estimate: **Unknown***

**Comment by Sunspot0411** [comment]
@Rubydesic Thanks for your replying. But this bug is already fixed a long time ago.  Next time hope you would comfirm if a bug/problem still exist before replying to bug report. Especially bugs has reported over 1 yeah
